services:
  mctemplates:
    build: .
    image: 1TheCrazy/mctemplates:latest
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env
    volumes:
      - "${SSL_DIR_HOST}:${SSL_DIR_CONTAINER}:ro"